pipeline {
    agent any

    stages {
        stage('Hello World') {
            steps {
                echo 'Hello, Sandeep! Jenkins is working.'
            }
        }
        stage('Install') {
            steps {
                dir('/home/azure/simple-node-js-react-npm-app') {
                    echo 'Installing dependencies...'
                    sh 'npm install'
                }
            }
        }

    }
}
