pipeline {
    agent any

    stages {
        stage('Hello World') {
            steps {
                echo 'Hello, Sandeep! Jenkins is working.'
            }
        }
        stage('Install') {
            steps {
                // We removed the 'dir' block. 
                // Jenkins will now work in its own safe folder.
                echo 'Installing dependencies...'
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'npm run build'
            }
        }
    }
}
